### ISSUE TITLE
select/4 and select/1 not running properly

### ISSUE THREAD

**Issue by walter-weinmann** [klarna/mnesia_eleveldb#10]
The project [kvs-stress](https://github.com/walter-weinmann/kvs_stress) tries to compare the performance of eleveldb, hanoidb, mnesia and mnesia_eleveldb in a pretty simple way.

You can easily vary the number of operations (2000, 5000, 10000, 20000, 50000, 100000), the size of data written (128, 256, 512, 1024 or 10248 bytes) or the transaction level - in case of mnesia -  (async_dirty, sync_dirty, sync_transaction, transaction). The examined operations are insert, lookup, range or traversal (`mnesia:select/4` and `mnesia:select/1`), update and delete. 

All tests are located in the following common test suite: `performance_SUITE.erl`. 

Different configurations can easily be achieved by commenting out test groups or test cases. 

I attached a pure mnesia version including mnesia_eleveldb with 2000 operations and data size about 10248 bytes [performance_SUITE.txt](https://github.com/klarna/mnesia_eleveldb/files/721892/performance_SUITE.txt)
and the corresponding html protocol 
[suite.log.txt](https://github.com/klarna/mnesia_eleveldb/files/721898/suite.log.txt) - both as simple TXT files. 

Running the same functions only differently configured, mnesia_eleveldb has problems with the range operation (= `mnesia:select/4` and `mnesia:select/1`). With `asny_dirty` and `sync_dirty` the error message is 

`**{mnesia_tm,non_transaction,746}**`, 

with `sync_transaction` and `transaction` the error message is 

`**{mnesia,wrap_trans,404}**`.    

Pure mnesia is running fine.

**Comment by mikpe** [comment]
Please describe exactly how to reproduce the errors.  "Running the same functions only differently configured" is a bit vague.

**Comment by walter-weinmann** [comment]
Please find attached a pretty focused eunit example (please rename from txt to erl) with both a mnesia and a mnesia_eleveldb test case. The core code base with insert/3, select/4 and select/1 is the same with both databases. I've also attached a log file from an exemplary run.

[source file](https://github.com/klarna/mnesia_eleveldb/files/732288/mnesia_eleveldb_select_4_1_test.txt)

[log file](https://github.com/klarna/mnesia_eleveldb/files/732289/logfile.txt)

**Comment by walter-weinmann** [comment]
The problem seems to be fixed with the latest 2 commits.
