### ISSUE TITLE
Badarg in ets:update_counter/3 when trying to insert many records

### ISSUE THREAD

**Issue by Lyr-a-Brode** [klarna/mnesia_eleveldb#11]
Hi!
I'm trying to insert lots of images into mnesia_eleveldb. Each image is 90Kb. After successfully inserting around 47000 records it all crashes with an error:
```
mnesia_eleveldb_speed_test: basic_test_ (module 'mnesia_eleveldb_speed_test')...*failed*
in function ets:update_counter/3
  called as update_counter(mnesia_stats,trans_log_writes_left,-1)
in call from mnesia_lib:incr_counter/2 (mnesia_lib.erl, line 600)
in call from mnesia_dumper:incr_log_writes/0 (mnesia_dumper.erl, line 68)
in call from mnesia_tm:do_dirty/2 (mnesia_tm.erl, line 1761)
in call from mnesia_tm:async_send_dirty/6 (mnesia_tm.erl, line 1998)
in call from mnesia_tm:dirty/2 (mnesia_tm.erl, line 1070)
in call from mnesia_eleveldb_speed_test:insert/2 (test/mnesia_eleveldb_speed_test.erl, line 33)
in call from mnesia_eleveldb_speed_test:loop/3 (test/mnesia_eleveldb_speed_test.erl, line 44)
**error:badarg
```
I dont know if I should ask somethere in otp community, since the error is about mnesia it seems.
Anyway, maybe you can suggest some way to fix this. It is also possible that I did something wrong.
The code of the test:
```
-module(mnesia_eleveldb_speed_test).

-export([test/0]).

-include_lib("eunit/include/eunit.hrl").

basic_test_() ->
    {timeout, 60000, fun test/0}.

test() ->
    mnesia:stop(),
    mnesia:delete_schema([node()]),
    mnesia:create_schema([node()], [{backend_types, [{ldb, mnesia_eleveldb}]}]),

    mnesia:start(),
    {atomic, ok} = mnesia:create_table(s, [{type, set},
                                            {record_name, x},
                                            {ldb, [node()]}]),

    {ok, Img} = file:read_file("/home/smilart/workspace/scripts/leveldb/img.jpg"),
    loop(0, 50000, Img),

    case mnesia:dirty_read({s, 30000}) of
        [] ->
            ?debugMsg("Nothing is written");
        [{_, K, V}] ->
            ?debugFmt("~p ~p~n", [K, V])
    end.


insert(S, Img) ->
        T0 = erlang:timestamp(),
        ok = mnesia:dirty_write(s, {x, S, Img}),
        T1 = erlang:timestamp(),
        if S rem 1000  == 0 ->
            ?debugFmt("~p ~p~n", [S, timer:now_diff(T1, T0)/1000]);

            true -> ok
        end.
    
loop(M, M, _) ->
    ok;
loop(S, M, Img) ->
    insert(S, Img),
    loop(S+1, M, Img).
```
Erlang/OTP 20 [erts-9.1], Ubuntu 16.04

**Comment by mikpe** [comment]
Thanks for the report, I'll try to take a look at it tomorrow.  Which version of eleveldb are you using?

**Comment by Lyr-a-Brode** [comment]
I pulled latest mnesia_eleveldb from "master" and it depends on eleveldb branch "develop". So I use the latest state of this branch.

**Comment by mikpe** [comment]
I cannot reproduce the issue, but according to your error stack dump, the error is in generic mnesia code and has nothing to do with mnesia_eleveldb.  Mnesia maintains a number of counters and at this point wants to decrement one of them.  That fails because the counter hasn't been initialized.

Presumably this would also happen with a disc_copies or disc_only_copies table.

Try initializing your mnesia DB with the following sequence:
``mnesia:create_schema([node()]),
    ok = application:start(mnesia, transient),
    {ok, ldb} = mnesia_eleveldb:register(ldb)``
before creating the table.

**Comment by Lyr-a-Brode** [comment]
Thanks, I'll try this.
