### ISSUE TITLE
the insert opration  is too slow than disc_only_copies' s table !

### ISSUE THREAD

**Issue by zhaohansprt** [klarna/mnesia_eleveldb#7]
# the compare test  
B=term_to_binary(lists:seq(99999,999999)).
(zhabc@localhost)43> size(B).
4500012
# leveldb_copies
(zhabc@localhost)10> mnesia:create_table(kv, [{attributes, record_info(fields, kv)},{leveldb_copies, [node()]}]). 
{atomic,ok}

 F=fun(X)-> mnesia:dirty_write(kv,#kv{k=X,v=B}) end. 
timer:tc(fun()->[F(X)||X<-lists:seq(200,299)] end).
{10259984,
 [ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,
  ok,ok,ok,ok,ok,ok,ok,ok|...]}
# disc_only_copies
(zhabc@localhost)53> mnesia:create_table(kv1, [{attributes, record_info(fields, kv1)}, {disc_only_copies, [node()]}]). 
{atomic,ok}
(zhabc@localhost)55> F3=fun(X)-> mnesia:dirty_write(kv1,#kv1{k=X,v=B}) end.
#Fun<erl_eval.6.52032458>
(zhabc@localhost)56> timer:tc(fun()->[F3(X)||X<-lists:seq(200,299)] end).       {2404449,                             
 [ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,
  ok,ok,ok,ok,ok,ok,ok,ok|...]}

**Comment by zhaohansprt** [comment]
First thanks for the  generous   opensouce !!!!
  the small bin's insert is nearly equel 
leveldb 7685 VS dets 6474
   but the  leveldb_copies doesn‘t work with ram's copy 

here is the smaller data insert test compare
# leveldb_copies
(zhabc@localhost)63> F7=fun(X)-> mnesia:dirty_write(kv,#kv{k=X,v= <<"sdfsdfdsf">>}) end.  
#Fun<erl_eval.6.52032458>
(zhabc@localhost)64> timer:tc(fun()->[F7(X)||X<-lists:seq(300,399)] end).      
 {7685,  
 [ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,
  ok,ok,ok,ok,ok,ok,ok,ok|...]}
# disc_only_copies

(zhabc@localhost)57> F5=fun(X)-> mnesia:dirty_write(kv1,#kv1{k=X,v= <<"fsdfsdf">>}) end.
#Fun<erl_eval.6.52032458>
(zhabc@localhost)58> timer:tc(fun()->[F5(X)||X<-lists:seq(300,399)] end).    
   {6474,  
 [ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,ok,
  ok,ok,ok,ok,ok,ok,ok,ok|...]}

**Comment by richcarl** [comment]
It's not unexpected that you'll see different read/write performance with eleveldb tables. The tradeoffs in LevelDB are very different from those in the Dets tables used by disk_only_copies. However, with eleveldb tables you can store huge amounts of data, whereas Dets has a hard limit of 2 GB (at which point the dets file becomes corrupted).

If there are any major bottlenecks in the Erlang implementation (for plain read and write operations), they are more likely to be in eleveldb itself than in the mnesia_eleveldb plugin. You could try writing the same amount of data to a raw eleveldb table (without going through mnesia), and compare with your mnesia measurements.

**Comment by richcarl** [comment]
Closing this for now. Reopen if you can show that there is a problem in the mnesia_eleveldb code itself.
