### ISSUE TITLE
Delete problem

### ISSUE THREAD

**Issue by walter-weinmann** [klarna/mnesia_eleveldb#8]
If key X is first inserted and then changed both with function `mnesia:write/3`, then key X can be deleted twice with function `mnesia: delete / 1`. This seems to be a result of eleveldb's delete mechanism.

**Comment by mikpe** [comment]
Please add a standalone test case illustrating the problem.

**Comment by walter-weinmann** [comment]
Sorry - it is a problem of the mnesia delete functions.
